collections:
  syllabus:
    output: true
defaults:
  - scope:
      path: ""
      type: syllabus
    values:
      layout: unit
      
docsUrl: "https://is.muni.cz/el/1421/podzim2016/VIKBB55/um/"
assessmentsUrl: "https://docs.google.com/spreadsheets/d/1TACu6UTlFanMzgDVqGjwGAAxft59XMqSsAfHHvFQQy0/edit?usp=sharing"
